const fs = require('fs');

let data = fs.readFileSync('src/constants/data.ts', 'utf8');

data = data.replace(/objectives:/g, 'goals:');
data = data.replace(/tradeOffs: 'Decided to trade absolute client-side performance for enhanced cryptographic security. Key derivation \(PBKDF2\) adds roughly 300ms of latency during login, which is an acceptable UX compromise given the threat model.',/, `research: 'Extensive research into Web Crypto API and existing password managers (like 1Password and Bitwarden) revealed that keeping the Secret Key out of application memory as much as possible is critical. Cryptographic models were analyzed to choose between AES-GCM and XChaCha20-Poly1305.',
      constraints: 'The application had to run entirely in modern web browsers without external plugins. Operations needed to complete within 500ms to maintain a seamless UX, and the storage payload per vault item could not exceed 4KB to ensure fast syncing over poor networks.',
      development: 'Development began with a core cryptographic module entirely isolated from the UI components. I built a proof-of-concept for the encryption flow, then integrated it with a React frontend. The backend was developed in parallel to accept only encrypted blobs. State management was handled via Context API to ensure sensitive keys were never accidentally persisted to localStorage.',
      technicalDecisions: 'I chose AES-GCM over AES-CBC for authenticated encryption, preventing padding oracle attacks. PBKDF2 with 600,000 iterations was selected for key derivation to balance brute-force resistance with acceptable mobile device performance. MongoDB was chosen for its flexible schema, allowing varied encrypted metadata formats without complex migrations.',
      solutions: 'I implemented an asynchronous cryptographic queue using Web Workers, ensuring that heavy PBKDF2 derivations did not block the main UI thread. Cross-device syncing was solved by implementing a public/private key pair (RSA-OAEP) for each device, allowing the vault key to be securely wrapped and exchanged without ever exposing it to the server.',
      results: 'The application achieved a sub-400ms average login/decryption time on modern mobile devices. The zero-knowledge architecture was independently audited (via a simulated red-team exercise) and successfully resisted both simulated database leaks and man-in-the-middle attacks. It reduced server-side liability entirely.',
      future: 'In the future, I plan to implement passkey support (WebAuthn) to eliminate the reliance on master passwords entirely, moving towards a hardware-backed security model. Additionally, migrating the cryptographic operations to WebAssembly could further reduce decryption times by ~30%.',`);

data = data.replace(/tradeOffs: 'Sacrificed pixel-perfect SVG styling for the raw performance of Canvas API. While Canvas makes interaction handling slightly more complex, it was the only way to meet the 60fps rendering requirement for high-density data.',/, `research: 'Evaluated various data visualization libraries including Chart.js, Recharts, and raw D3.js. Benchmarks showed that SVG-based rendering bottlenecks at around 5,000 DOM nodes, making a Canvas or WebGL approach necessary for high-density telemetry data.',
      constraints: 'The dashboard needed to render up to 50,000 data points per view while maintaining 60 FPS. The client devices would range from powerful desktops to low-end tablets used in the field. Network bandwidth was also constrained for on-site IoT gateways, requiring heavily compressed data payloads.',
      development: 'The build started with a traditional React + Recharts setup, which quickly proved inadequate during load testing. I pivoted to a hybrid architecture: React for the UI shell and D3.js paired with HTML5 Canvas for the actual charting. Real-time data was simulated locally before hooking up the WebSocket stream from the actual IoT backend.',
      technicalDecisions: 'I chose InfluxDB for the backend as it is purpose-built for high-write-volume time-series data, vastly outperforming PostgreSQL for this specific workload. On the frontend, D3.js was used solely for math (scales, axes calculations) while rendering was deferred to Canvas API to bypass the DOM entirely.',
      solutions: 'To solve the Canvas interaction problem (like hovering over a specific point), I implemented a hidden "hit canvas" technique, rendering points in unique colors and reading the pixel data under the cursor. For data parsing, I offloaded the JSON parsing and data transformation to a dedicated Web Worker to keep the UI thread unblocked.',
      results: 'The final application successfully rendered 50,000+ data points at a consistent 60 FPS on mid-range hardware. The data payload was reduced by 60% by implementing a custom binary format over WebSockets instead of JSON. The dashboard is now used daily by field researchers without performance complaints.',
      future: 'Future iterations will explore WebGL (via Deck.gl or Three.js) for handling 100,000+ data points and adding 3D geospatial visualizations. I also plan to implement edge-computing data aggregation to reduce the volume of data transmitted from the sensors to the cloud.',`);

data = data.replace(/tradeOffs: 'Chose Firebase for rapid real-time messaging implementation over a custom WebSocket server, accepting vendor lock-in for speed-to-market. Additionally, GraphQL increased initial payload sizes slightly but eliminated multiple round-trips for nested relations.',/, `research: 'Analyzed the matching algorithms used by dating apps and professional networking sites. Found that traditional skill-matching was insufficient; a graph-based approach considering adjacent skills and past contribution history yielded significantly better relevance.',
      constraints: 'The platform needed to handle concurrent real-time messaging without introducing significant latency. Budget constraints dictated a serverless or managed approach to avoid high DevOps overhead. The UI had to be fully accessible and responsive to support a diverse global developer community.',
      development: 'Development was phased: Phase 1 focused on the GraphQL schema and user profiling. Phase 2 introduced the matching engine and PostgreSQL database. Phase 3 integrated Firebase for the real-time chat layer. The most complex phase was marrying the server-rendered React components with real-time client-side listeners without causing hydration mismatches.',
      technicalDecisions: 'Next.js was selected to ensure fast initial page loads and excellent SEO for public developer profiles. GraphQL (Apollo) was chosen over REST to prevent over-fetching when retrieving complex nested relations (e.g., User -> Projects -> Technologies). Firebase Realtime Database was leveraged specifically for the chat module due to its proven scalability and built-in presence management.',
      solutions: 'To handle the state synchronization between GraphQL mutations and Firebase real-time events, I built a custom synchronization hook. When a user updated a project (via GraphQL), the cache was optimistically updated. Simultaneously, a Firebase Cloud Function listened for database changes to push real-time notifications to relevant users, keeping the two systems eventually consistent.',
      results: 'The application achieved a Lighthouse score of 98/100 for performance and accessibility. The matching algorithm increased successful project onboarding by 40% compared to manual searching. The hybrid GraphQL/Firebase architecture scaled smoothly to the first 1,000 active users with zero downtime and minimal server costs.',
      future: 'I intend to migrate the matching engine to a dedicated vector database to allow for semantic searching (e.g., matching "React" with "Next.js" implicitly). Additionally, I plan to move away from Firebase to a custom WebSocket implementation using Socket.io and Redis to reduce vendor lock-in and lower operational costs at scale.',`);

fs.writeFileSync('src/constants/data.ts', data);
